version: 1.0.{build}

image: Visual Studio 2013

init:
- git config --global core.autocrlf input

environment:
  matrix:
  - platform: x86
    VS_ARCH: Visual Studio 12 2013 Win64
  - platform: x64
    VS_ARCH: Visual Studio 12 2013

build_script:
- mkdir build
- cd build
- cmake -G "%VS_ARCH%" "-DVER=%APPVEYOR_BUILD_VERSION%" ..
- cmake --build .
- cpack

artifacts:
- path: build/winfstest-*.zip
  name: zip
